### ISSUE TITLE
설명보기 - 음식점

### ISSUE THREAD

**Issue by sungwonnoh** [9oormthon-univ/2024_DANPOONG_TEAM_21_FE#5]
## 설명보기_음식점
실습하기와 같은 레이아웃 사용
가로모드 설정

## To-do
- [x] 옵션 라우팅 설정
- [x] 가로모드 설정
- [x] 컴포넌트 단위로 나누기
- [x] 장바구니
- [x] 모달 창 구현
- [x] 알림 창 구현
- [x] 주문 완료 화면
